name: Publish

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - feat/ci-cd # Should always fire on this branch for testing
  release:
    types:
      - published
      - released
      - prereleased
      - edited
  create:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: installing go packages
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.2'
          cache: false
      - name: Run go tests
        run: go test ./...
      - name: Build package
        run: |
          go build -C ./src -ldflags="-X main.Version=${{ github.ref_name }}" \
            -v -o ~/gt
          CGO_ENABLED=0 GOOS=linux go build -C ./src \
            -ldflags="-extldflags=-static -X main.Version=${{ github.ref_name }}" \
            -tags netgo \
            -v -o ~/gt-static
      - name: Publish standard package
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v7
        with:
          name: linux-x64-gt-latest
          path: ~/gt
          if-no-files-found: error
          retention-days: 30
          archive: false
          overwrite: true
      - name: Publish static package
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v7
        with:
          name: linux-x64-gt-static-latest
          path: ~/gt-static
          if-no-files-found: error
          retention-days: 30
          archive: false
          overwrite: true
      - name: Generate hashes
        run: |
          sha256sum ~/gt >> ~/checksum.txt
          sha256sum ~/gt-static >> ~/checksum.txt
      - name: Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: |
            ~/gt
            ~/gt-static
            ~/checksum.txt
        env:
          GITHUB_TOKEN: ${{ github.token }}
