name: Unit-Testing

on:
  workflow_dispatch:
  push:
    branches:
      - feat/ci-cd
  pull_request:
    branches:
      - dev
      - main

jobs:
  static-code:
    runs-on: ubuntu-latest
    steps:
      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.26.4
          go-package: ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: run linter
        uses: golangci/golangci-lint-action@v9
        with:
          skip-cache: true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: installing go packages
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.4'
          cache: false
      - name: Run tests
        run: go test ./... -race
      - name: Vet files
        run: go vet ./...
