name: Unit-Testing

on:
  workflow_dispatch:
  push:
    branches:
      - feat/ci-cd
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: Cache Go modules
        uses: actions/cache@v5
        with:
          path: |
            ~/go/pkg/mod
            ~/go/pkg/build
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: run linter
        uses: golangci/golangci-lint-action@v9
        with:
          skip-cache: true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: Cache Go modules
        uses: actions/cache@v5
        with:
          path: |
            ~/go/pkg/mod
            ~/go/pkg/build
          key: ${{ runner.os }}-go-lint-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-lint-
      - name: installing go packages
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.2'
          cache: false
