name: Unit-Testing

on:
  workflow_dispatch:
  pull_request:

    branches:
      - dev
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: run linter
        uses: golangci/golangci-lint-action@v9

  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: installing go packages
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.2'
      - name: run static code analysis
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          install-go: false

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: Cache Go modules
        id: cache-go
        uses: actions/cache@v5
        env:
          cache-name: cache-go-deps
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.cache-name }}
            ${{ runner.os }}-go-
            ${{ runner.os }}-

      - if: ${{ steps.cache-go.outputs.cache-hit != 'true' }}
        name: List the state of the package cache
        continue-on-error: true
        run: echo "Found cache!"
      - name: installing go packages
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.2'
      - name: Run go tests
        run: go test ./...